// <auto-generated />
namespace Advanced_Csharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialstage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialstage));
        
        string IMigrationMetadata.Id
        {
            get { return "201709220809005_Initial-stage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
